Fixed typos in the backend documentation
forem/forem-docs pull request #105
Opened 2023-04-05 18:33 UTC by AbrahamRH

### Description

- fix some spelling errors in backend documents
- Fixes [#104](https://github.com/forem/forem-docs/issues/104)

### Type
- Typo errors

### Screenshots

![typo error in configuration.md](https://i.imgur.com/IkwKzMK.png)

![typo errors in authentication](https://i.imgur.com/RTz24gt.png)

2023-04-05 18:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/forem/forem-docs?pullRequest=105) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/forem/forem-docs?pullRequest=105) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/forem/forem-docs?pullRequest=105) it.</sub>

2023-04-07 12:01 UTC, rt4914 requested changes
Thanks a lot @AbrahamRH for this PR.

I have suggested one change. 

You can also contribute on our main repo https://github.com/forem/forem/issues if you are interested. Thanks :-)

2023-04-07 12:01 UTC, rt4914 commented on docs/backend/database.md
> +use `MODE=STARTER` skipping the creation of all sample data i.e.
I thinks this and its below change cane be reverted as the current documentation looks correct here.

2023-04-10 10:31 UTC, rt4914 approved these changes
Looks good to me. Thanks for your contribution 🎉

2023-04-10 18:51 UTC, maestromac approved these changes

2023-04-10 18:52 UTC, merged